version: '3'

services:
  backend:
    build: .
    command: bash -c "python migrate.py && python run.py"
    depends_on:
      - database
    restart: on-failure
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@database:5432/test_db
      DEBUG: 0
      ACCESS_TOKEN_EXPIRES_MINUTES: 60
      REFRESH_TOKEN_EXPIRES_DAYS: 1
      SECRET_KEY: supersecret
      INITIAL_USER_USERNAME: user
      INITIAL_USER_PASSWORD: user
      LOAD_MOCK: 1
    ports:
      - 8000:8000
  database:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test_db
      volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
