"""create tables for purchases

Revision ID: 1e3c68d3bf22
Revises: 8d25a722eb2b
Create Date: 2023-02-20 19:04:23.147335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3c68d3bf22'
down_revision = '8d25a722eb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_uuid', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_product',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('product_cost', sa.Float(), nullable=False),
    sa.Column('summary_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('purchase_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_product')
    op.drop_table('purchase')
    # ### end Alembic commands ###
